version: '3.8'
services:
  frontend:
    image: nginx
    restart: always
    ports: 
      - '80:80'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
